[package]
name = "yew-attrs-macro"
description = "Dynamic attributes for Yew."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
once_cell = "1.19.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.74", features = ["full", "extra-traits"] }

[dev-dependencies]
indexmap = "2.4.0"
tokio = { version = "1.39.2", features = ["full"] }
trybuild = "1.0.99"
yew = { workspace = true, features = ["ssr"] }
# yew-attrs = { version = "0.2.3" }
yew-attrs = { path = "../yew-attrs" }
