[workspace]
members = ["packages/*"]
resolver = "2"

[workspace.package]
authors = ["Rust For Web <info@rustforweb.org>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/RustForWeb/yew-attrs"
version = "0.2.4"

[workspace.dependencies]
yew = "0.21.0"
