[package]
name = "yew-attrs"
description = "Dynamic attributes for Yew."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
indexmap = "2.4.0"
thiserror = "1.0.63"
yew.workspace = true
yew-attrs-macro = { path = "../yew-attrs-macro", version = "0.2.4" }
